'use client';

import { useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { Truck } from 'lucide-react';
import { DashboardShell } from '@/components/dashboard-shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { formatRupiah } from '@/lib/marketplace';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

const blank = { display_name: '', vehicle_type: 'motor_roda_tiga', rate_per_km: '', service_area: '', contact: '' };
export default function LogisticsRegistrationPage() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [provider, setProvider] = useState<any>(null); const [form, setForm] = useState(blank); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { (async () => { try { const currentProfile = await getCurrentUserProfile(); if (!currentProfile || currentProfile.role !== 'recycler') return router.replace('/dashboard'); setProfile(currentProfile); const { data, error } = await supabase.from('logistics_providers').select('*').eq('owner_id', currentProfile.id).maybeSingle(); if (error) setMessage(error.message); if (data) { setProvider(data); setForm({ display_name: data.display_name, vehicle_type: data.vehicle_type, rate_per_km: String(data.rate_per_km), service_area: data.service_area, contact: data.contact }); } } catch { router.replace('/login'); } finally { setLoading(false); } })(); }, [router]);
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setMessage(''); const payload = { owner_id: profile.id, display_name: form.display_name, vehicle_type: form.vehicle_type, rate_per_km: Number(form.rate_per_km), service_area: form.service_area, contact: form.contact }; const result = provider ? await supabase.from('logistics_providers').update(payload).eq('id', provider.id).select('*').single() : await supabase.from('logistics_providers').insert(payload).select('*').single(); setSaving(false); if (result.error || !result.data) return setMessage(result.error?.message || 'Pendaftaran armada belum dapat disimpan.'); setProvider(result.data); setMessage('Data armada disimpan. Status awal menunggu verifikasi BioLoop.'); }
  if (loading) return <main className="work-loading">Memuat pendaftaran armada…</main>;
  return <DashboardShell role="recycler" name={profile?.full_name || profile?.name} points={Number(profile?.total_points ?? profile?.points ?? 0)} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><main className="market-page logistics-page"><header className="seller-head"><div><p className="work-kicker">LAYANAN OPSIONAL · ARMADA LOKAL</p><h2>Daftarkan armada untuk pickup material organik.</h2><p>Armada bukan peran akun terpisah. Pemilik Viar, Tossa, atau mobil bak dapat menampilkan jasa pickup setelah data diverifikasi.</p></div></header>{message && <p className="work-form-error">{message}</p>}<section className="seller-listing-layout"><Card className="seller-product-form"><CardHeader><div><CardTitle>{provider ? 'Perbarui armada Anda' : 'Pendaftaran armada'}</CardTitle><p>Tarif per kilometer akan dipakai sebagai dasar estimasi saat buyer memilih armada lokal.</p></div><Truck size={18} className="work-card-icon" /></CardHeader><CardContent><form className="seller-form" onSubmit={submit}><label>Nama armada atau usaha<input required value={form.display_name} onChange={(event) => setForm({ ...form, display_name: event.target.value })} placeholder="Contoh: Angkut Cilandak" /></label><div className="seller-form-grid"><label>Jenis kendaraan<select value={form.vehicle_type} onChange={(event) => setForm({ ...form, vehicle_type: event.target.value })}><option value="motor_roda_tiga">Motor roda tiga (Viar/Tossa)</option><option value="mobil_bak">Mobil bak terbuka</option><option value="lainnya">Kendaraan lain</option></select></label><label>Tarif dasar per km<input required min="0" type="number" value={form.rate_per_km} onChange={(event) => setForm({ ...form, rate_per_km: event.target.value })} placeholder="3000" /></label></div><label>Area layanan<input required value={form.service_area} onChange={(event) => setForm({ ...form, service_area: event.target.value })} placeholder="Contoh: Jakarta Selatan dan sekitarnya" /></label><label>Kontak operasional<input required value={form.contact} onChange={(event) => setForm({ ...form, contact: event.target.value })} placeholder="Nomor WhatsApp atau telepon bisnis" /></label><Button disabled={saving}>{saving ? 'Menyimpan…' : provider ? 'Simpan perubahan' : 'Daftarkan armada'}</Button></form></CardContent></Card><aside className="seller-form-aside"><Card><CardHeader><div><CardTitle>Status layanan</CardTitle><p>Verifikasi membantu menjaga keamanan pickup material.</p></div></CardHeader><CardContent>{provider ? <div className="logistics-status"><span>Status</span><b>{provider.verification_status}</b><span>Tarif</span><b>{formatRupiah(Number(provider.rate_per_km))}/km</b><span>Visibilitas</span><b>{provider.is_active ? 'Aktif di checkout' : 'Belum aktif'}</b></div> : <p className="market-empty">Belum ada armada yang didaftarkan dari akun ini.</p>}</CardContent></Card></aside></section></main></DashboardShell>;
}
