/* Recycler dashboard — supply intelligence, claims, analytics, and completed material history. */
'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, MapPin } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { DashboardShell, StatusPill } from '@/components/dashboard-shell';
import { CompletedHistory, MapCard, WeeklyChart } from '@/components/dashboard-visuals';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { completedListings, type DashboardListing, weeklySeries } from '@/lib/dashboard-data';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

export default function RecyclerDashboard() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [open, setOpen] = useState<DashboardListing[]>([]); const [owned, setOwned] = useState<DashboardListing[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [claiming, setClaiming] = useState<string | null>(null); const points = Number(profile?.total_points ?? profile?.points ?? 0); const series = useMemo(() => weeklySeries(owned, 'created'), [owned]); const completed = completedListings(owned); const openKg = open.reduce((sum, item) => sum + Number(item.weight_kg || 0), 0);
  async function load(id: string) { const [supply, mine] = await Promise.all([supabase.from('waste_listings').select('*').in('status', ['available', 'pending']).order('created_at', { ascending: false }), supabase.from('waste_listings').select('*').eq('processor_id', id).order('created_at', { ascending: false })]); if (supply.error) setMessage(supply.error.message); else setOpen(supply.data || []); if (mine.error) setMessage(mine.error.message); else setOwned(mine.data || []); }
  useEffect(() => { async function init() { try { const current = await getCurrentUserProfile(); if (!current || current.role !== 'recycler') return router.replace('/dashboard'); setProfile(current); await load(current.id); } catch { router.replace('/login'); } finally { setLoading(false); } } init(); }, [router]);
  async function claim(item: DashboardListing) { if (!profile?.id) return; setClaiming(item.id); const { data, error } = await supabase.from('waste_listings').update({ status: 'claimed', processor_id: profile.id }).eq('id', item.id).in('status', ['available', 'pending']).select('*').maybeSingle(); setClaiming(null); if (error) return setMessage(error.message); if (!data) return setMessage('Listing tidak tersedia untuk diklaim.'); setOpen((items) => items.filter((entry) => entry.id !== item.id)); setOwned((items) => [data, ...items]); }
  if (loading) return <main className="work-loading">Memuat ruang kerja…</main>;
  return <DashboardShell role="recycler" name={profile?.full_name || profile?.name} points={points} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><div className="work-content" id="ringkasan"><section className="recycler-lead"><div><p className="work-kicker">PASOKAN ORGANIK</p><h2>Pilih bahan.<br />Jalankan siklus.</h2></div><p>Material tersedia, klaim aktif, dan catatan hasil pengolahan berada pada satu ruang kerja yang mudah dipindai.</p><span className="work-live"><i /> pembaruan langsung</span></section><section className="work-metrics recycler-metrics"><article><span>Pasokan terbuka</span><b>{open.length}</b><small>{openKg.toLocaleString('id-ID')} kg tersedia</small></article><article><span>Dalam proses</span><b>{owned.filter((item) => item.status !== 'completed').length}</b><small>Sudah masuk klaim Anda</small></article><article id="poin"><span>Poin BioLoop</span><b>{points.toLocaleString('id-ID')}</b><small>Saldo dari profil Anda</small></article></section><section className="work-asymmetric recycler-map-row"><MapCard listings={open} note={`${open.length} sumber bahan tersedia`} /><WeeklyChart data={series} title="Material diklaim" accent="#7d9f7c" /></section><Card className="claim-board"><CardHeader><div><CardTitle>Pasokan masuk</CardTitle><p>Pilih bahan berdasarkan kapasitas pengolahan saat ini.</p></div><span className="work-panel-count">{open.length} tersedia</span></CardHeader><CardContent><div className="claim-grid">{open.map((item) => <article key={item.id}><div><StatusPill status={item.status} /><h3>{item.waste_type}</h3><p><MapPin size={14} /> {item.location_name || 'Lokasi belum dicantumkan'}</p></div><div><b>{Number(item.weight_kg || 0).toLocaleString('id-ID')}<small> kg</small></b><Button size="sm" disabled={claiming === item.id} onClick={() => claim(item)}>{claiming === item.id ? 'Mengklaim…' : <>Klaim <ArrowUpRight size={14} /></>}</Button></div></article>)}{!open.length && <p className="work-empty">Belum ada pasokan yang siap diklaim.</p>}</div>{message && <p className="work-form-error">{message}</p>}</CardContent></Card><CompletedHistory listings={completed} title="Riwayat bahan selesai diolah" /></div></DashboardShell>;
}
