'use client';

import { useEffect, useMemo, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Leaf, Scale, Wind } from 'lucide-react';
import { DashboardShell } from '@/components/dashboard-shell';
import { Card, CardContent } from '@/components/ui/card';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

export default function BuyerImpactPage() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [personal, setPersonal] = useState<any[]>([]); const [national, setNational] = useState<any>(null); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true);
  useEffect(() => { (async () => { try { const currentProfile = await getCurrentUserProfile(); if (!currentProfile || currentProfile.role !== 'recycler') return router.replace('/dashboard'); setProfile(currentProfile); const [personalResult, nationalResult] = await Promise.all([supabase.from('order_impacts').select('*').eq('buyer_id', currentProfile.id), supabase.rpc('get_bioloop_national_impact')]); if (personalResult.error || nationalResult.error) setMessage((personalResult.error || nationalResult.error)?.message || 'Data dampak belum tersedia.'); setPersonal(personalResult.data || []); setNational(nationalResult.data || null); } catch { router.replace('/login'); } finally { setLoading(false); } })(); }, [router]);
  const totals = useMemo(() => personal.reduce((acc, item) => ({ weight: acc.weight + Number(item.processed_weight_kg || 0), co2: acc.co2 + Number(item.co2e_saved_kg || 0), methane: acc.methane + Number(item.methane_prevented_kg || 0) }), { weight: 0, co2: 0, methane: 0 }), [personal]);
  if (loading) return <main className="work-loading">Memuat dampak Anda…</main>;
  return <DashboardShell role="recycler" name={profile?.full_name || profile?.name} points={Number(profile?.total_points ?? profile?.points ?? 0)} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><main className="market-page impact-page"><header className="seller-head"><div><p className="work-kicker">DAMPAK SIRKULAR</p><h2>Material yang Anda terima dan olah kembali.</h2><p>Ringkasan ini bertambah ketika buyer mengonfirmasi berat akhir pada order selesai.</p></div></header>{message && <p className="work-form-error">{message}</p>}<section className="impact-stat-grid"><Card><CardContent><Scale size={19} /><span>Material Anda</span><b>{totals.weight.toLocaleString('id-ID')} kg</b></CardContent></Card><Card><CardContent><Leaf size={19} /><span>CO₂e terhitung</span><b>{totals.co2.toLocaleString('id-ID')} kg</b></CardContent></Card><Card><CardContent><Wind size={19} /><span>Metana dicegah</span><b>{totals.methane.toLocaleString('id-ID')} kg</b></CardContent></Card></section><section className="impact-national"><p className="work-kicker">AKUMULASI BIOLOOP</p><h3>Dampak seluruh transaksi yang sudah terukur.</h3><div><article><span>Material dialihkan</span><b>{Number(national?.processed_weight_kg || 0).toLocaleString('id-ID')} kg</b></article><article><span>CO₂e terhitung</span><b>{Number(national?.co2e_saved_kg || 0).toLocaleString('id-ID')} kg</b></article><article><span>Order selesai</span><b>{Number(national?.completed_orders || 0).toLocaleString('id-ID')}</b></article></div></section><p className="certificate-note">Faktor aplikasi menggunakan 2,5 kg CO₂e dan 0,6 kg metana dicegah per kilogram material dengan berat akhir yang dikonfirmasi. Ini adalah estimasi pelacakan produk dan bukan klaim kredit karbon tersertifikasi.</p></main></DashboardShell>;
}
