/* Admin workspace — compact system visibility with map context and exception-led operations. */
'use client';

import dynamic from 'next/dynamic';
import { useEffect, useState } from 'react';
import { Activity, AlertTriangle, Building2, ClipboardCheck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { DashboardNotice, DashboardShell, OpsMetric, OpsPanel, StatusPill } from '@/components/dashboard-shell';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

const MapWorkspace = dynamic(() => import('@/components/Map'), { ssr: false, loading: () => <div className="ops-map-loading">Memuat peta operasi…</div> });
type Listing = { id: string; waste_type: string; weight_kg: number; location_name: string; status: string; created_at: string; lat?: number; lng?: number };

export default function AdminDashboard() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [listings, setListings] = useState<Listing[]>([]); const [partnerCount, setPartnerCount] = useState(0); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const points = Number(profile?.total_points ?? profile?.points ?? 0);
  useEffect(() => { async function init() { try { const current = await getCurrentUserProfile(); if (!current || current.role !== 'admin') return router.replace('/dashboard'); setProfile(current); const [listingResult, profileResult] = await Promise.all([supabase.from('waste_listings').select('*').order('created_at', { ascending: false }), supabase.from('profiles').select('*', { count: 'exact', head: true })]); if (listingResult.error) setMessage(listingResult.error.message); else setListings(listingResult.data || []); if (!profileResult.error) setPartnerCount(profileResult.count || 0); } catch { router.replace('/login'); } finally { setLoading(false); } } init(); }, [router]);
  if (loading) return <main className="ops-loading">Menyiapkan workspace…</main>; const open = listings.filter((item) => ['available', 'pending'].includes(item.status)); const transit = listings.filter((item) => ['claimed', 'in_transit'].includes(item.status)); const completed = listings.filter((item) => item.status === 'completed');
  return <DashboardShell role="admin" name={profile?.full_name || profile?.name} points={points} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><div id="ringkasan" className="ops-page-heading"><div><p>OPERATIONS CENTER</p><h2>Alur sistem</h2></div><span className="ops-live"><i /> Sistem aktif</span></div><div className="ops-metric-grid"><OpsMetric label="Mitra" value={partnerCount} tone="ink" /><OpsMetric label="Listing terbuka" value={open.length} tone="amber" /><OpsMetric label="Dalam proses" value={transit.length} tone="clay" /><OpsMetric label="Selesai" value={completed.length} tone="sage" /></div><div className="ops-work-grid"><OpsPanel id="peta" title="Sebaran operasi" action={<span className="ops-panel-note">{listings.length} listing</span>}><MapWorkspace locations={listings} /></OpsPanel><OpsPanel title="Perlu perhatian" action={<AlertTriangle size={17} className="ops-heading-icon" />}><div className="ops-queue">{open.slice(0, 4).map((item) => <article key={item.id} className="ops-queue-row"><div className="ops-queue-icon"><ClipboardCheck size={16} /></div><div><strong>{item.location_name || 'Lokasi belum diisi'}</strong><p>{item.waste_type} · {Number(item.weight_kg).toLocaleString('id-ID')} kg</p></div><StatusPill status={item.status} /></article>)}{!open.length && <p className="ops-empty">Tidak ada listing yang tertahan.</p>}</div></OpsPanel></div><OpsPanel id="aktivitas" title="Aktivitas terbaru" action={<Activity size={17} className="ops-heading-icon" />}>{message && <DashboardNotice>{message}</DashboardNotice>}<div className="ops-table">{listings.slice(0, 9).map((item) => <article key={item.id}><div><strong>{item.waste_type}</strong><span>{item.location_name || 'Lokasi belum diisi'}</span></div><span>{Number(item.weight_kg).toLocaleString('id-ID')} kg</span><StatusPill status={item.status} /></article>)}{!listings.length && <p className="ops-empty">Belum ada aktivitas sistem.</p>}</div></OpsPanel></DashboardShell>;
}
