/* Admin dashboard — system signal, operational history, and real ecosystem activity. */
'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, AlertTriangle, Building2, CircleCheckBig } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { DashboardShell, StatusPill } from '@/components/dashboard-shell';
import { CompletedHistory, MapCard, WeeklyChart } from '@/components/dashboard-visuals';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { completedListings, type DashboardListing, weeklySeries } from '@/lib/dashboard-data';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

export default function AdminDashboard() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [listings, setListings] = useState<DashboardListing[]>([]); const [partnerCount, setPartnerCount] = useState(0); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const points = Number(profile?.total_points ?? profile?.points ?? 0); const completed = useMemo(() => completedListings(listings), [listings]); const series = useMemo(() => weeklySeries(listings, 'completed'), [listings]);
  useEffect(() => { async function init() { try { const current = await getCurrentUserProfile(); if (!current || current.role !== 'admin') return router.replace('/dashboard'); setProfile(current); const [listingResult, partnerResult] = await Promise.all([supabase.from('waste_listings').select('*').order('created_at', { ascending: false }), supabase.rpc('get_bioloop_admin_partner_count')]); if (listingResult.error) setMessage(listingResult.error.message); else setListings(listingResult.data || []); if (partnerResult.error) setMessage(partnerResult.error.message); else setPartnerCount(Number(partnerResult.data || 0)); } catch { router.replace('/login'); } finally { setLoading(false); } } init(); }, [router]);
  if (loading) return <main className="work-loading">Memuat ruang kerja…</main>; const open = listings.filter((item) => ['available', 'pending'].includes(item.status)); const transit = listings.filter((item) => ['claimed', 'in_transit'].includes(item.status));
  return <DashboardShell role="admin" name={profile?.full_name || profile?.name} points={points} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><div className="work-content" id="ringkasan"><section className="admin-head"><div><p className="work-kicker">OPERATIONS CENTER</p><h2>Aliran kota,<br />dalam satu pandangan.</h2></div><div className="admin-live"><i /> sistem beroperasi</div></section><section className="work-metrics admin-metrics"><article><span>Mitra aktif</span><b>{partnerCount}</b><small>Profile terdaftar</small></article><article><span>Perlu diproses</span><b>{open.length}</b><small>Listing terbuka</small></article><article><span>Dalam siklus</span><b>{transit.length}</b><small>Klaim atau dalam rute</small></article></section><section className="work-asymmetric admin-asymmetric"><MapCard listings={listings} note={`${listings.length} listing tercatat di sistem`} /><WeeklyChart data={series} title="Penyelesaian mingguan" accent="#a2741b" unit="listing" /></section><Card className="admin-watch"><CardHeader><div><CardTitle>Perlu perhatian</CardTitle><p>Listing yang belum bergerak ke tahap berikutnya.</p></div><AlertTriangle size={18} className="work-card-icon" /></CardHeader><CardContent><div className="admin-watch-list">{open.slice(0, 7).map((item) => <article key={item.id}><div><strong>{item.waste_type}</strong><p>{item.location_name || 'Lokasi belum dicantumkan'} · {Number(item.weight_kg || 0).toLocaleString('id-ID')} kg</p></div><StatusPill status={item.status} /></article>)}{!open.length && <p className="work-empty">Tidak ada listing yang menunggu perhatian.</p>}</div>{message && <p className="work-form-error">{message}</p>}</CardContent></Card><CompletedHistory listings={completed} title="Riwayat siklus yang selesai" /></div></DashboardShell>;
}
