'use client';

import dynamic from 'next/dynamic';
import type { CSSProperties } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { CalendarCheck2, MapPinned } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import type { DashboardListing } from '@/lib/dashboard-data';
import { StatusPill } from '@/components/dashboard-shell';
const WorkspaceMap = dynamic(() => import('@/components/Map'), { ssr: false, loading: () => <div className="work-map-loading">Memuat peta…</div> });

export function WeeklyChart({ data, title, accent = '#c4623a', unit = 'kg' }: { data: { label: string; jumlah: number; kg: number }[]; title: string; accent?: string; unit?: 'kg' | 'listing' }) { const key = unit === 'kg' ? 'kg' : 'jumlah'; return <Card className="work-chart-card"><CardHeader><div><CardTitle>{title}</CardTitle><p>5 minggu terakhir</p></div><span className="work-chart-legend" style={{ '--dot': accent } as CSSProperties}>{unit === 'kg' ? 'Berat' : 'Aktivitas'}</span></CardHeader><CardContent><div className="work-chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data} margin={{ top: 10, right: 6, left: -25, bottom: 0 }}><defs><linearGradient id={`gradient-${accent.replace('#', '')}`} x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor={accent} stopOpacity={.28} /><stop offset="100%" stopColor={accent} stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#ede9e2" strokeDasharray="3 4" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#8a8279' }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 10, fill: '#8a8279' }} /><Tooltip cursor={{ stroke: '#bdb6ad', strokeWidth: 1 }} contentStyle={{ border: '1px solid #e3ddd4', borderRadius: 8, fontSize: 11 }} formatter={(value) => [unit === 'kg' ? `${Number(value).toLocaleString('id-ID')} kg` : value, unit === 'kg' ? 'Berat' : 'Listing']} /><Area type="monotone" dataKey={key} stroke={accent} strokeWidth={2.5} fill={`url(#gradient-${accent.replace('#', '')})`} /></AreaChart></ResponsiveContainer></div></CardContent></Card>; }
export function MapCard({ listings, note }: { listings: DashboardListing[]; note: string }) { return <Card id="peta" className="work-map-card"><CardHeader><div><CardTitle>Peta operasi</CardTitle><p>{note}</p></div><MapPinned size={18} className="work-card-icon" /></CardHeader><CardContent><WorkspaceMap locations={listings} /></CardContent></Card>; }
export function CompletedHistory({ listings, title = 'Selesai diterima' }: { listings: DashboardListing[]; title?: string }) { return <Card id="riwayat" className="work-history-card"><CardHeader><div><CardTitle>{title}</CardTitle><p>Aktivitas yang sudah tuntas</p></div><CalendarCheck2 size={18} className="work-card-icon" /></CardHeader><CardContent><div className="work-history">{listings.slice(0, 6).map((item) => <article key={item.id}><div className="work-history-mark" /><div><strong>{item.waste_type}</strong><span>{item.location_name || 'Lokasi tidak dicantumkan'} · {new Intl.DateTimeFormat('id-ID', { day: 'numeric', month: 'short' }).format(new Date(item.completed_at || item.created_at))}</span></div><b>{Number(item.weight_kg || 0).toLocaleString('id-ID')} kg</b><StatusPill status={item.status} /></article>)}{!listings.length && <p className="work-empty">Belum ada riwayat penyelesaian.</p>}</div></CardContent></Card>; }
