import Link from 'next/link';
import type * as React from 'react';
import { ArrowUpRight, Check, MapPin, PackageCheck } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { fulfillmentSteps, formatRupiah, type MarketplaceOrder } from '@/lib/marketplace';

export function OrderProgress({ status }: { status: string }) { const activeIndex = fulfillmentSteps.findIndex((item) => item.status === status); const current = activeIndex < 0 ? 0 : activeIndex; return <div className="market-progress">{fulfillmentSteps.map((step, index) => <div className={index <= current ? 'done' : ''} key={step.status}><i>{index < current ? <Check size={11} /> : index + 1}</i><section><strong>{step.label}</strong><span>{index === current ? step.detail : ''}</span></section></div>)}</div>; }
export function OrderCard({ order, href, action }: { order: MarketplaceOrder; href: string; action?: React.ReactNode }) { return <Card className="market-order-card"><CardContent><div className="market-order-top"><span>ORDER #{order.id.slice(0, 8).toUpperCase()}</span><b>{order.fulfillment_status.replaceAll('_', ' ')}</b></div><div className="market-order-info"><div><strong>{order.waste_listings?.waste_type || 'Material organik'}</strong><p><MapPin size={13} /> {order.waste_listings?.location_name || order.buyer_location_name || 'Lokasi belum dicantumkan'}</p></div><strong>{Number(order.quantity_kg).toLocaleString('id-ID')} kg</strong></div><div className="market-order-bottom"><span>{formatRupiah(order.total_amount)}</span>{action || <Button asChild size="sm" variant="outline"><Link href={href}>Lacak <ArrowUpRight size={14} /></Link></Button>}</div></CardContent></Card>; }
export function MarketplaceMaterialCard({ listing, href }: { listing: { id: string; waste_type: string; weight_kg: number; location_name: string; price_per_kg?: number; material_grade?: string | null; intended_use?: string | null }; href: string }) { return <Card className="material-card"><CardContent><span>{listing.material_grade || 'Terverifikasi'}</span><h3>{listing.waste_type}</h3><p><MapPin size={13} /> {listing.location_name || 'Lokasi belum dicantumkan'}</p><div><strong>{Number(listing.weight_kg).toLocaleString('id-ID')}<small> kg tersedia</small></strong><b>{formatRupiah(Number(listing.price_per_kg || 0))}<small>/kg</small></b></div><p className="material-use">Cocok untuk: {listing.intended_use || 'BSF, kompos, pakan, dan pemanfaatan organik lain'}</p><Button asChild size="sm"><Link href={href}>Lihat & checkout <ArrowUpRight size={14} /></Link></Button></CardContent></Card>; }
