/* Driver workspace — a route-led pickup console with map context and one-tap status progression. */
'use client';

import dynamic from 'next/dynamic';
import { useEffect, useState } from 'react';
import { CheckCheck, Navigation, Route, Truck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { DashboardNotice, DashboardShell, OpsMetric, OpsPanel, StatusPill } from '@/components/dashboard-shell';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

const MapWorkspace = dynamic(() => import('@/components/Map'), { ssr: false, loading: () => <div className="ops-map-loading">Memuat peta operasi…</div> });
type Job = { id: string; waste_type: string; weight_kg: number; location_name: string; status: string; created_at: string; lat?: number; lng?: number };

export default function DriverDashboard() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [jobs, setJobs] = useState<Job[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [updatingId, setUpdatingId] = useState<string | null>(null); const points = Number(profile?.total_points ?? profile?.points ?? 0);
  async function loadJobs() { const { data, error } = await supabase.from('waste_listings').select('*').in('status', ['claimed', 'in_transit']).order('created_at', { ascending: true }); if (error) setMessage(error.message); else setJobs(data || []); }
  useEffect(() => { async function init() { try { const current = await getCurrentUserProfile(); if (!current || current.role !== 'driver') return router.replace('/dashboard'); setProfile(current); await loadJobs(); } catch { router.replace('/login'); } finally { setLoading(false); } } init(); }, [router]);
  async function advance(job: Job) { const nextStatus = job.status === 'claimed' ? 'in_transit' : 'completed'; setUpdatingId(job.id); setMessage(''); const { data, error } = await supabase.from('waste_listings').update({ status: nextStatus }).eq('id', job.id).select('*').single(); setUpdatingId(null); if (error) return setMessage(error.message); if (!data) return setMessage('Status belum mengembalikan data.'); if (nextStatus === 'completed') setJobs((items) => items.filter((item) => item.id !== job.id)); else setJobs((items) => items.map((item) => item.id === job.id ? data : item)); setMessage(nextStatus === 'completed' ? 'Penjemputan selesai.' : 'Rute dimulai.'); }
  if (loading) return <main className="ops-loading">Menyiapkan workspace…</main>; const ready = jobs.filter((job) => job.status === 'claimed'); const moving = jobs.filter((job) => job.status === 'in_transit'); const totalKg = jobs.reduce((sum, job) => sum + Number(job.weight_kg || 0), 0);
  return <DashboardShell role="driver" name={profile?.full_name || profile?.name} points={points} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><div id="ringkasan" className="ops-page-heading"><div><p>RUTE HARI INI</p><h2>Penjemputan aktif</h2></div><span className="ops-live"><i /> {moving.length ? 'Dalam rute' : 'Siap jalan'}</span></div><div className="ops-metric-grid"><OpsMetric label="Siap diambil" value={ready.length} tone="amber" /><OpsMetric label="Dalam perjalanan" value={moving.length} tone="clay" /><OpsMetric label="Muatan aktif" value={`${totalKg.toLocaleString('id-ID')} kg`} tone="sage" /><OpsMetric label="Poin BioLoop" value={points} tone="ink" /></div><div className="ops-work-grid"><OpsPanel id="peta" title="Peta rute" action={<span className="ops-panel-note">{jobs.length} pemberhentian</span>}><MapWorkspace locations={jobs} /></OpsPanel><OpsPanel title="Berikutnya" action={<Navigation size={17} className="ops-heading-icon" />}><div className="ops-next-job">{jobs[0] ? <><div className="ops-next-number">01</div><h3>{jobs[0].location_name || 'Lokasi belum diisi'}</h3><p>{jobs[0].waste_type}</p><strong>{Number(jobs[0].weight_kg).toLocaleString('id-ID')} kg</strong><StatusPill status={jobs[0].status} /></> : <p className="ops-empty">Tidak ada rute aktif.</p>}</div></OpsPanel></div><OpsPanel id="aktivitas" title="Antrean rute" action={<span className="ops-panel-note">Urutkan berdasarkan waktu klaim</span>}>{message && <DashboardNotice>{message}</DashboardNotice>}<div className="ops-route-list">{jobs.map((job, index) => <article key={job.id}><span className="ops-route-order">{String(index + 1).padStart(2, '0')}</span><div><strong>{job.location_name || 'Lokasi belum diisi'}</strong><p>{job.waste_type} · {Number(job.weight_kg).toLocaleString('id-ID')} kg</p></div><StatusPill status={job.status} /><button className="ops-claim-button" disabled={updatingId === job.id} onClick={() => advance(job)}>{updatingId === job.id ? 'Memperbarui…' : job.status === 'claimed' ? 'Mulai rute' : 'Selesaikan'}</button></article>)}{!jobs.length && <p className="ops-empty">Belum ada penjemputan aktif.</p>}</div></OpsPanel></DashboardShell>;
}
