/* Driver dashboard — route execution with real completion attribution, history, and weekly workload. */
'use client';

import { useEffect, useMemo, useState } from 'react';
import { ArrowUpRight, CheckCircle2, Navigation, Route, Truck } from 'lucide-react';
import { useRouter } from 'next/navigation';
import { DashboardShell, StatusPill } from '@/components/dashboard-shell';
import { CompletedHistory, MapCard, WeeklyChart } from '@/components/dashboard-visuals';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { completedListings, type DashboardListing, weeklySeries } from '@/lib/dashboard-data';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

export default function DriverDashboard() {
  const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [jobs, setJobs] = useState<DashboardListing[]>([]); const [history, setHistory] = useState<DashboardListing[]>([]); const [loading, setLoading] = useState(true); const [message, setMessage] = useState(''); const [updating, setUpdating] = useState<string | null>(null); const points = Number(profile?.total_points ?? profile?.points ?? 0); const series = useMemo(() => weeklySeries(history, 'completed'), [history]); const next = jobs[0];
  async function load(driverId: string) { const [active, done] = await Promise.all([supabase.from('waste_listings').select('*').in('status', ['claimed', 'in_transit']).order('created_at', { ascending: true }), supabase.from('waste_listings').select('*').eq('driver_id', driverId).eq('status', 'completed').order('completed_at', { ascending: false })]); if (active.error) setMessage(active.error.message); else setJobs(active.data || []); if (done.error) setMessage(done.error.message); else setHistory(done.data || []); }
  useEffect(() => { async function init() { try { const current = await getCurrentUserProfile(); if (!current || current.role !== 'driver') return router.replace('/dashboard'); setProfile(current); await load(current.id); } catch { router.replace('/login'); } finally { setLoading(false); } } init(); }, [router]);
  async function advance(job: DashboardListing) { if (!profile?.id) return; const status = job.status === 'claimed' ? 'in_transit' : 'completed'; setUpdating(job.id); setMessage(''); const payload = status === 'completed' ? { status, driver_id: profile.id, completed_at: new Date().toISOString() } : { status, driver_id: profile.id }; const { error } = await supabase.from('waste_listings').update(payload).eq('id', job.id).in('status', ['claimed', 'in_transit']); setUpdating(null); if (error) return setMessage(error.message); if (status === 'completed') { const finished = { ...job, ...payload }; setJobs((rows) => rows.filter((item) => item.id !== job.id)); setHistory((rows) => [finished, ...rows]); } else setJobs((rows) => rows.map((item) => item.id === job.id ? { ...item, ...payload } : item)); }
  if (loading) return <main className="work-loading">Memuat ruang kerja…</main>; const transit = jobs.filter((item) => item.status === 'in_transit'); const ready = jobs.filter((item) => item.status === 'claimed'); const activeKg = jobs.reduce((sum, item) => sum + Number(item.weight_kg || 0), 0);
  return <DashboardShell role="driver" name={profile?.full_name || profile?.name} points={points} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><div className="work-content" id="ringkasan"><section className="driver-top"><div><p className="work-kicker">RUTE & PENJEMPUTAN</p><h2>Bawa satu<br />rute sampai tuntas.</h2></div><Card className="driver-km"><CardContent><span>MUATAN AKTIF</span><b>{activeKg.toLocaleString('id-ID')}<small> kg</small></b><p>{jobs.length} pemberhentian menunggu pembaruan</p></CardContent></Card></section><section className="driver-layout"><Card className="driver-next"><CardHeader><div><CardTitle>Berikutnya</CardTitle><p>Prioritas rute saat ini</p></div><Navigation size={18} className="work-card-icon" /></CardHeader><CardContent>{next ? <div className="next-dark"><span>01</span><h3>{next.location_name || 'Lokasi belum dicantumkan'}</h3><p>{next.waste_type}</p><strong>{Number(next.weight_kg || 0).toLocaleString('id-ID')}<small> kg</small></strong><StatusPill status={next.status} /><Button variant="default" className="driver-action" disabled={updating === next.id} onClick={() => advance(next)}>{updating === next.id ? 'Memperbarui…' : next.status === 'claimed' ? <>Mulai rute <ArrowUpRight size={15} /></> : <>Selesaikan <CheckCircle2 size={15} /></>}</Button></div> : <p className="work-empty">Belum ada rute aktif.</p>}</CardContent></Card><MapCard listings={jobs} note={`${jobs.length} titik rute aktif`} /></section><section className="work-metrics driver-metrics"><article><span>Siap diambil</span><b>{ready.length}</b><small>Menunggu mulai rute</small></article><article><span>Dalam perjalanan</span><b>{transit.length}</b><small>Masih aktif hari ini</small></article><article id="poin"><span>Poin BioLoop</span><b>{points.toLocaleString('id-ID')}</b><small>Saldo dari profil Anda</small></article></section><section className="work-asymmetric"><WeeklyChart data={series} title="Penjemputan selesai" accent="#4a7d83" unit="listing" /><Card className="route-board"><CardHeader><div><CardTitle>Antrean rute</CardTitle><p>Urutkan berdasarkan waktu klaim</p></div><Route size={18} className="work-card-icon" /></CardHeader><CardContent>{jobs.map((job, index) => <article key={job.id} className="route-row"><span>{String(index + 1).padStart(2, '0')}</span><div><strong>{job.location_name || 'Lokasi belum dicantumkan'}</strong><p>{job.waste_type} · {Number(job.weight_kg || 0).toLocaleString('id-ID')} kg</p></div><StatusPill status={job.status} /><Button variant="outline" size="sm" disabled={updating === job.id} onClick={() => advance(job)}>{job.status === 'claimed' ? 'Mulai' : 'Selesai'}</Button></article>)}{!jobs.length && <p className="work-empty">Tidak ada antrean aktif.</p>}{message && <p className="work-form-error">{message}</p>}</CardContent></Card></section><CompletedHistory listings={history} title="Riwayat pengantaran selesai" /></div></DashboardShell>;
}
