'use client';
import { useEffect, useState, type FormEvent } from 'react';
import { useRouter } from 'next/navigation';
import { DashboardShell, StatusPill } from '@/components/dashboard-shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { Plus, Tag } from 'lucide-react';

export default function ProducerListingsPage() { const router=useRouter(); const [profile,setProfile]=useState<any>(null); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [message,setMessage]=useState(''); const [form,setForm]=useState({waste_type:'Sisa dapur dan makanan siap olah',weight_kg:'',location_name:'',price_per_kg:'',material_grade:'Layak olah',intended_use:'BSF, pakan ikan, atau kompos'});
useEffect(()=>{(async()=>{try{const p=await getCurrentUserProfile();if(!p||p.role!=='producer')return router.replace('/dashboard');setProfile(p);const {data,error}=await supabase.from('waste_listings').select('*').eq('producer_id',p.id).order('created_at',{ascending:false});if(error)setMessage(error.message);else setItems(data||[])}catch{router.replace('/login')}finally{setLoading(false)}})()},[router]);
async function submit(e:FormEvent){e.preventDefault();setSaving(true);setMessage('');const {data,error}=await supabase.from('waste_listings').insert({producer_id:profile.id,waste_type:form.waste_type,weight_kg:Number(form.weight_kg),location_name:form.location_name,price_per_kg:Number(form.price_per_kg),material_grade:form.material_grade,intended_use:form.intended_use,status:'available'}).select('*').single();setSaving(false);if(error)return setMessage(error.message);setItems((v)=>[data,...v]);setForm({...form,weight_kg:'',location_name:'',price_per_kg:''})}
if(loading)return <main className="work-loading">Memuat listing…</main>;return <DashboardShell role="producer" name={profile?.full_name||profile?.name} points={Number(profile?.total_points??profile?.points??0)} onSignOut={async()=>{await signOutUser();router.replace('/login')}}><main className="market-page"><header className="market-head"><div><p className="work-kicker">INVENTARIS PRODUCER</p><h2>Listing material</h2><p>Publikasikan material terpilah secara terpisah dari pesanan dan pelacakan.</p></div></header><section className="market-grid"><Card><CardHeader><div><CardTitle>Listing baru</CardTitle><p>Harga akan terlihat di marketplace sebelum buyer checkout.</p></div><Plus size={18} className="work-card-icon"/></CardHeader><CardContent><form className="checkout-form" onSubmit={submit}><label>Jenis material<select value={form.waste_type} onChange={e=>setForm({...form,waste_type:e.target.value})}><option>Sisa dapur dan makanan siap olah</option><option>Kulit buah dan sayur</option><option>Ampas tahu atau kelapa</option><option>Sisa olahan daging dan ikan</option></select></label><label>Lokasi pickup<input required value={form.location_name} onChange={e=>setForm({...form,location_name:e.target.value})}/></label><div className="order-meta"><label>Berat tersedia<input required min="1" type="number" value={form.weight_kg} onChange={e=>setForm({...form,weight_kg:e.target.value})}/></label><label>Harga per kg<input required min="0" type="number" value={form.price_per_kg} onChange={e=>setForm({...form,price_per_kg:e.target.value})}/></label></div><label>Penggunaan yang direkomendasikan<input value={form.intended_use} onChange={e=>setForm({...form,intended_use:e.target.value})}/></label>{message&&<p className="work-form-error">{message}</p>}<Button disabled={saving}>{saving?'Mempublikasikan…':'Publikasikan ke marketplace'}</Button></form></CardContent></Card><Card className="market-side-card"><CardHeader><div><CardTitle>Aturan harga</CardTitle><p>Harga per kilogram dipakai untuk subtotal checkout buyer.</p></div><Tag size={18} className="work-card-icon"/></CardHeader><CardContent><div className="market-callout">Ongkos pickup dan biaya layanan dihitung pada checkout sebagai baris terpisah. Nilai tersebut tidak mengubah harga material Anda.</div></CardContent></Card></section><section className="market-stack" style={{marginTop:18}}>{items.map(item=><Card key={item.id}><CardContent><div className="market-rows"><article><div><strong>{item.waste_type}</strong><p>{item.location_name} · {Number(item.weight_kg).toLocaleString('id-ID')} kg · Rp{Number(item.price_per_kg||0).toLocaleString('id-ID')}/kg</p></div><StatusPill status={item.status}/></article></div></CardContent></Card>)}{!items.length&&<p className="market-empty">Belum ada listing yang dipublikasikan.</p>}</section></main></DashboardShell> }
