'use client';

import { use, useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { MessageCircleMore, UsersRound } from 'lucide-react';
import { DashboardShell } from '@/components/dashboard-shell';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { getCurrentUserProfile, signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';

export default function PoolingGroupPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = use(params); const router = useRouter(); const [profile, setProfile] = useState<any>(null); const [group, setGroup] = useState<any>(null); const [members, setMembers] = useState<any[]>([]); const [messages, setMessages] = useState<any[]>([]); const [body, setBody] = useState(''); const [message, setMessage] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  async function load() { try { const currentProfile = await getCurrentUserProfile(); if (!currentProfile || currentProfile.role !== 'recycler') return router.replace('/dashboard'); setProfile(currentProfile); const [groupResult, memberResult, messageResult] = await Promise.all([supabase.from('pooling_groups').select('*,waste_listings(waste_type,location_name)').eq('id', id).maybeSingle(), supabase.from('pooling_members').select('*').eq('pooling_group_id', id), supabase.from('pooling_messages').select('*').eq('pooling_group_id', id).order('created_at', { ascending: true })]); if (groupResult.error || memberResult.error || messageResult.error) setMessage((groupResult.error || memberResult.error || messageResult.error)?.message || 'Grup belum dapat dimuat.'); setGroup(groupResult.data); setMembers(memberResult.data || []); setMessages(messageResult.data || []); } catch { router.replace('/login'); } finally { setLoading(false); } }
  useEffect(() => { load(); }, [id]);
  async function send(event: FormEvent) { event.preventDefault(); if (!body.trim()) return; setSaving(true); const { error } = await supabase.from('pooling_messages').insert({ pooling_group_id: id, sender_id: profile.id, body: body.trim() }); setSaving(false); if (error) return setMessage(error.message); setBody(''); await load(); }
  if (loading) return <main className="work-loading">Memuat koordinasi angkut…</main>; if (!group) return <main className="work-loading">Grup patungan tidak ditemukan.</main>;
  const reservedWeight = members.reduce((total, member) => total + Number(member.reserved_weight_kg || 0), 0);
  return <DashboardShell role="recycler" name={profile?.full_name || profile?.name} points={Number(profile?.total_points ?? profile?.points ?? 0)} onSignOut={async () => { await signOutUser(); router.replace('/login'); }}><main className="market-page pooling-page"><header className="seller-head"><div><p className="work-kicker">PATUNGAN ANGKUT</p><h2>Koordinasikan volume dan pickup bersama.</h2><p>Grup ini dibuat dari order material yang sama. Hanya anggota grup yang dapat melihat percakapan ini.</p></div><Button asChild variant="outline"><Link href="/dashboard/recycler/orders">Pesanan saya</Link></Button></header>{message && <p className="work-form-error">{message}</p>}<section className="pooling-layout"><Card><CardHeader><div><CardTitle>{group.waste_listings?.waste_type || 'Material organik'}</CardTitle><p>{group.waste_listings?.location_name || 'Lokasi seller'} · tujuan area {group.pickup_area || 'belum diisi'}</p></div><UsersRound size={18} className="work-card-icon" /></CardHeader><CardContent><div className="pooling-numbers"><div><span>Target angkut</span><b>{Number(group.target_weight_kg).toLocaleString('id-ID')} kg</b></div><div><span>Sudah terpesan</span><b>{reservedWeight.toLocaleString('id-ID')} kg</b></div><div><span>Anggota</span><b>{members.length}</b></div></div><p className="checkout-note">Gunakan ruang ini untuk menyepakati waktu dan armada. Pembayaran dan berat akhir tetap diselesaikan pada order masing-masing.</p></CardContent></Card><Card className="pooling-chat"><CardHeader><div><CardTitle>Koordinasi anggota</CardTitle><p>Pesan disimpan untuk grup ini.</p></div><MessageCircleMore size={18} className="work-card-icon" /></CardHeader><CardContent><div className="pooling-messages">{messages.map((item) => <article key={item.id} className={item.sender_id === profile.id ? 'self' : ''}><p>{item.body}</p><small>{new Date(item.created_at).toLocaleString('id-ID', { hour: '2-digit', minute: '2-digit', day: 'numeric', month: 'short' })}</small></article>)}{!messages.length && <p className="market-empty">Belum ada pesan. Mulai koordinasi kebutuhan angkut dengan anggota grup.</p>}</div><form className="pooling-send" onSubmit={send}><input value={body} onChange={(event) => setBody(event.target.value)} placeholder="Tulis pesan koordinasi…" maxLength={1000} /><Button disabled={saving}>{saving ? 'Mengirim…' : 'Kirim'}</Button></form></CardContent></Card></section></main></DashboardShell>;
}
