'use client';
import { useEffect,useState } from 'react';
import { useRouter } from 'next/navigation';
import { DashboardShell } from '@/components/dashboard-shell';
import { MarketplaceMaterialCard } from '@/components/marketplace-components';
import { getCurrentUserProfile,signOutUser } from '@/lib/auth';
import { supabase } from '@/lib/supabase';
import { Search } from 'lucide-react';

export default function RecyclerMarketplacePage(){const router=useRouter();const [profile,setProfile]=useState<any>(null);const [items,setItems]=useState<any[]>([]);const [q,setQ]=useState('');const [loading,setLoading]=useState(true);const [message,setMessage]=useState('');useEffect(()=>{(async()=>{try{const p=await getCurrentUserProfile();if(!p||p.role!=='recycler')return router.replace('/dashboard');setProfile(p);const {data,error}=await supabase.from('waste_listings').select('*').in('status',['available','pending']).order('created_at',{ascending:false});if(error)setMessage(error.message);else setItems(data||[])}catch{router.replace('/login')}finally{setLoading(false)}})()},[router]);if(loading)return <main className="work-loading">Memuat marketplace…</main>;const shown=items.filter(i=>`${i.waste_type} ${i.location_name} ${i.intended_use||''}`.toLowerCase().includes(q.toLowerCase()));return <DashboardShell role="recycler" name={profile?.full_name||profile?.name} points={Number(profile?.total_points??profile?.points??0)} onSignOut={async()=>{await signOutUser();router.replace('/login')}}><main className="market-page"><header className="market-head"><div><p className="work-kicker">BIOLOOP MARKETPLACE</p><h2>Material organik terpilah</h2><p>Temukan sumber bahan untuk BSF, pakan akuakultur, kompos, dan pemanfaatan sirkular lain.</p></div><label className="checkout-form" style={{minWidth:230}}><span>Temukan material</span><input placeholder="Jenis atau lokasi" value={q} onChange={e=>setQ(e.target.value)}/></label></header>{message&&<p className="work-form-error">{message}</p>}<section className="market-listing-grid">{shown.map(item=><MarketplaceMaterialCard key={item.id} listing={item} href={`/dashboard/recycler/marketplace/${item.id}/checkout`}/>)}</section>{!shown.length&&<p className="market-empty">Belum ada material yang sesuai pencarian.</p>}</main></DashboardShell>}
